---
#Mytransics application pool settings.
#authentication to qa.mytransics.com
#api keys, ports and secrets based on qa.mytransics.com

#config :
  domain_name: "mytransics.com"
  cloud_host_name: "qa"

  servers:
    -
      url: mongo

  mytransics:
    authenticationEndpoint: "http://localhost:10081"
    authenticationUri: "/api"
    apiEndpointExternalApi: "https://qa.mytransics.com/api"
    domain : "https://qa.mytransics.com"
    environmentRibbon: "QA"

    service:
      hostUri: /service
      port: 17081
      authenticationRedirectKey: txservice
      authenticationApiKey: aBwNjAAX8BU759UJMQAHf9eP
      authenticationApiSecret: 5svNdFj4uNAeDVi6GRWmG6iE
      endpoints:
        -
          id: mytransics
          host: https://qa.mytransics.com/api/v2/
          debug: true
        -
          id: txmytransics
          host: https://qa.mytransics.com/api/v2/
          debug: true
        -
          id: dwh
          host: https://qa_dwhrestapi.transics.com/api/v1/
          debug: true
        -
          id: skycc
          host: https://qa.mytransics.com/skycc/api/v1/
          debug: true
      title: TX-SERVICE
      cssFile: txservice.css
      jsFile: txservice.min.js
      cdnUrl: https://dev.mytransics.com/cdn/0.16/0
      settings:
        environment: "qa"
        transicsStockId: 6541
        defaultPackageType: "production"
        helpfile: ""
        isSFMS: false
